Scribe_notes lecture 2
jhofman/msd2019-notes pull request #2
Opened 2019-02-06 01:34 UTC by FanHuang321

2019-02-06 22:46 UTC, redouane-dziri requested changes
Please follow the templates provided. You should change template.tex and not include all the surrounding commands in your notes but rather include mostly your notes. Please also insert your figures in a `figures` folder within your folder. And follow the notation used by other scribes with no capital letters in your folder name

2019-02-07 00:29 UTC, FanHuang321 commented
Updated lecture2 notes

2019-02-07 00:46 UTC, redouane-dziri commented
I realize my last comment wasn't as clear as I wanted it to be. 
Your notes' content should be in a file uni.tex as before your last changes 
BUT you should link it to template.tex as others did (you can look at other folders for reference) so that uni.tex contains only the notes themselves (with figures in your case)
I hope this is clearer, thanks!

2019-02-07 04:42 UTC, FanHuang321 commented
updated !!

2019-02-07 14:17 UTC, merged

2019-02-07 14:34 UTC, jhofman commented
@FanHuang321, there are several bugs in your LaTeX, your document isn't compiling. Can you please fix and issue a new pull request?

If you're new to writing in LaTeX, you can see Overleaf's guide here:

  https://www.overleaf.com/learn/latex/Creating_a_document_in_LaTeX

And if you're having trouble compiling LaTeX on your machine, you can use the Overleaf editor online here:

  https://www.overleaf.com/docs?snip_uri=http:%2F%2Fjakehofman.com%2Ftmp%2Ftemplate.zip

Please resubmit once you have a document that compiles on your end.

2019-02-07 14:38 UTC, jhofman reviewed
I've left some notes on things to fix.

This isn't everything, but should give you a start.

2019-02-07 14:38 UTC, jhofman commented on lecture_2/fh2386/fh2386.tex
> +\begin{documents}
this should be a \begin{\itemize} to start a list instead of \begin{documents}

there's another instance of this below

2019-02-07 14:38 UTC, jhofman commented on lecture_2/fh2386/fh2386.tex
> +\ITEM{\textbf{5\% margin}} margin of error means 5\% standard error or 5\% standard deviation in sampling distribution for the mean.
\item should be in lowercase

2019-02-07 14:38 UTC, jhofman commented on lecture_2/fh2386/fh2386.tex
> + p\_hat\<-\ replicate(1e5,mean(rbinom(n,1,p))\\
Here's how you can include verbatim R code in LaTeX without having to escape things:

https://www.overleaf.com/learn/latex/Questions/How_do_I_include_sections_of_R_code_within_my_LaTeX_document%3F

2019-02-07 14:45 UTC, redouane-dziri commented
(I should've checked the content more thoroughly, mostly focused on structure, my bad!)